[package]
name = "grim-rs"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Nevsky <hopperplayer0@gmail.com>"]
description = "Wayland screenshot library and CLI using zwlr_screencopy_manager_v1 (grim-like, but in Rust)"
license = "MIT"
repository = "https://github.com/vremayvnikuda/grim-rs"
homepage = "https://github.com/vremayvnikuda/grim-rs"
documentation = "https://docs.rs/grim-rs"
readme = "README.md"
keywords = ["wayland", "screenshot", "grim", "cli", "library"]
categories = ["command-line-utilities", "graphics", "os::unix-apis"]
exclude = [".gitignore", ".github/", "target/", "examples/"]

[dependencies]
wayland-client = "0.31.1"
wayland-protocols = { version = "0.31.0", features = ["client"] }
wayland-protocols-wlr = { version = "0.2.0", features = ["client"] }
wayland-cursor = "0.31.0"
xkbcommon = "0.7.0"
log = "0.4.20"
env_logger = "0.10.1"
image = "0.24.7"
chrono = "0.4.34"
tempfile = "3.10.1"
libc = "0.2"
smithay-client-toolkit = "0.16"
cairo-rs = "0.18"
tokio = { version = "1.36", features = ["full"] }

[dev-dependencies]
tempfile = "3.10.1"